language: objective-c
osx_image: xcode7.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - brew update
  - brew reinstall xctool
xcode_scheme: Debug
xcode_sdk:
  - iphonesimulator9.2
script:
  - xcodebuild -showsdks
  - xctool -project Project/Hexagon.xcodeproj -scheme Debug -sdk iphonesimulator9.2 build analyze
  
